### ISSUE TITLE
重复发信以及对评论的回复发信但不成功

### ISSUE THREAD

**Issue by xbstory** [uniartisan/CommentToMail#2]
使用的主题是：https://github.com/youranreus/G
环境是 php7.0-fpm+nginx+mysql
> https://github.com/youranreus/G/blob/b015c5471696ec1449181e11847472316ca260d1/comments.php#L76

添加代码的结果如下：
```php
                  <input type="text" name="author" id="author" placeholder="称呼" value="<?php $this->remember('author'); ?>" />
                  <input type="email" name="mail" id="mail" placeholder="电子邮件" value="<?php $this->remember('mail'); ?>" />
                  <input type="hidden" name="receiveMail" id="receiveMail" value="yes" />
                  <input type="text" name="url" id="url" placeholder="网站"  value="<?php $this->remember('url'); ?>" />
```
设置了所有评论都需要审核，在添加一条测试评论后（隐身模式），执行了发送任务地址，此时正常收到评论提醒邮件。
在登录后台后，通过了待审核的测试评论，打开了文章，并对待审核评论进行了回复，此时再次执行发送任务地址，显示发送成功，但是并没有收到邮件。
在隐身模式下替换了原有的测试邮件地址为新邮件地址，再次添加了一个新评论，此时执行发送任务地址，发现重复发送之前测试的评论提醒，以及本次新评论。
再次回复新评论，执行发送任务地址，依然提示成功（发送任务地址接口返回），但实际没有发出邮件。

**Comment by xbstory** [comment]
补充：后台回复评论后执行发送任务地址也是显示成功但实际没有成功。
使用的是smtp，谷歌邮箱，已开启允许低安全性。

**Comment by xbstory** [comment]
改用LoveKKComment了

**Comment by zhiyuan1i** [comment]
> 补充：后台回复评论后执行发送任务地址也是显示成功但实际没有成功。
> 使用的是smtp，谷歌邮箱，已开启允许低安全性。

您好，您可以开启日志，并关闭立即清理数据库。在复现显示已经发送后查看数据库日志，并查看谷歌邮箱已发送邮件。
```
        Typecho_Plugin::factory('Widget_Feedback')->finishComment = array('CommentToMail_Plugin', 'parseComment');
        Typecho_Plugin::factory('Widget_Comments_Edit')->finishComment = array('CommentToMail_Plugin', 'parseComment');
        Typecho_Plugin::factory('Widget_Comments_Edit')->mark = array('CommentToMail_Plugin', 'passComment');
```
插件利用 Typecho 的钩子，将后台数据库的操作记录。部分个人邮箱不允许快速重复发信。

**确认是设计 bug**

**Comment by zhiyuan1i** [comment]
已经在最新版本修复，新增强制忽略用户选择。

**Comment by if1y** [comment]
你好，我也遇到了同样的问题，情况也很类似
主题也是 G
环境为宝塔面板 php7.0+Nginx+SQLite
发信邮箱是 QQ域名邮箱

- 已添加 代码到正确位置
- 访问发信地址有数量和id变化（说明发件信息返回给插件成功）
- 插件自带的发信测试功能正常（应该说明smtp信息无误）
- 模拟无痕评论时，发信邮箱不增加已发送（使用插件自带测试时有增加）

也尝试了勾选强制忽略，还是不行
@uniartisan

**Comment by uniartisan** [comment]
> 你好，我也遇到了同样的问题，情况也很类似
> 主题也是 G
> 环境为宝塔面板 php7.0+Nginx+SQLite
> 发信邮箱是 QQ域名邮箱
> 
> * 已添加 代码到正确位置
> * 访问发信地址有数量和id变化（说明发件信息返回给插件成功）
> * 插件自带的发信测试功能正常（应该说明smtp信息无误）
> * 模拟无痕评论时，发信邮箱不增加已发送（使用插件自带测试时有增加）
> 
> 也尝试了勾选强制忽略，还是不行
> @uniartisan

您好，能否通过邮箱私信通讯地址以便于通过数据库日志定位问题。
我的邮箱： lizhiyuan@uniartisan.com

**Comment by zhiyuan1i** [comment]
> 你好，我也遇到了同样的问题，情况也很类似
> 主题也是 G
> 环境为宝塔面板 php7.0+Nginx+SQLite
> 发信邮箱是 QQ域名邮箱
> 
> * 已添加 代码到正确位置
> * 访问发信地址有数量和id变化（说明发件信息返回给插件成功）
> * 插件自带的发信测试功能正常（应该说明smtp信息无误）
> * 模拟无痕评论时，发信邮箱不增加已发送（使用插件自带测试时有增加）
> 
> 也尝试了勾选强制忽略，还是不行
> @uniartisan


您好，已经定位问题。

确定问题在于 *腾讯反垃圾逻辑* 。插件默认是连续无间隔发送队列邮件，对于腾讯个人/企业/域名邮箱来说，会触发反垃圾逻辑。

即：**插件正常向SMTP服务器发送邮件队列，SMTP服务器返回成功代码，但实际被拦截。**

开发代码已经完成虚拟机测试，在完成选项开发和服务器测试后会再次发版。

**Comment by zhiyuan1i** [comment]
已发布新版。
