### ISSUE TITLE
[建议] 评论通过后发送邮件

### ISSUE THREAD

**Issue by xbstory** [uniartisan/CommentToMail#3]
建议：评论通过后发送邮件
补充说明：

今天后知后觉，发现网友回复网友的的评论，会直接发送邮件提醒到被回复的邮箱。

对于这种被回复者不是网站站长的，能不能增加一个评论通过后再给被回复的人发送邮件的设定，当然给站长的邮件提醒应当及时送达。

**Comment by zhiyuan1i** [comment]
> 建议：评论通过后发送邮件
> 补充说明：
> 
> 今天后知后觉，发现网友回复网友的的评论，会直接发送邮件提醒到被回复的邮箱。
> 
> 对于这种被回复者不是网站站长的，能不能增加一个评论通过后再给被回复的人发送邮件的设定，当然给站长的邮件提醒应当及时送达。

不好意思现在才有时间看到Issue。

您的问题是指：
* 回复者不是网站站长的，评论未通过后也给被回复的人发送邮件

改进措施是：
* 回复者不是网站站长的，评论需要通过后也给被回复的人发送邮件
* 回复者给站长，立即发送邮件

我会抽出时间确定这个设计缺陷，确认后在可预见的将来排期并修复这个问题。

**Comment by xbstory** [comment]
感谢回复，辛苦了！

**Comment by zhiyuan1i** [comment]
> 感谢回复，辛苦了！

>现网友回复网友的的评论，会直接发送邮件提醒到被回复的邮箱。
对于这种被回复者不是网站站长的，能不能增加一个评论通过后再给被回复的人发送邮件的设定

这个指的是b给a留下评论，即便b这次的评论还没有通过也给a发了邮件吗？
我自己测试的时候，没有通过的邮件没有发送到a的邮箱。由于生产环境中phpmyadmin被禁用了，暂时不方便调试

**Comment by xbstory** [comment]
是这个现象，明天我再测试一次。

**Comment by xbstory** [comment]
不好意思现在才回复，出现这个问题是因为我同时开启了另一个插件导致的...打扰了
